apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
  - name: container
    image: image
    volumeMounts:
    - name: volume
      mountPath: /path/to/mount
  volumes:
  - name: volume
    emptyDir: {}