apiVersion: v1
kind: Pod
metadata:
  name: app-livenessProbe
spec:
  containers:
  - name: app-container
    image: myapp-image
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5