apiVersion: apps/v1
kind: Pod
metadata:
  name: app-multicontainer
  labels:
    app: app-multicontainer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-multicontainer
  template:
    metadata:
      labels:
        app: app-multicontainer
    spec:
      containers:
      - name: container-1
        image: nginx
        ports:
        - containerPort: 80
      - name: container-2
        image: busybox
        command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']
      restartPolicy: Always