apiVersion: v1
kind: Pod
metadata:
  name: app-secret-env
type: Opaque
data:
  API_KEY: <insert-Base64-encoded-value-here>
  DB_URL: <insert-Base64-encoded-value-here>
  PASSWORD: <insert-Base64-encoded-value-here>
